### PR TITLE
Makes it compatible (deprecation errors free) with PHP 8.*

### PR DESCRIPTION
**Pull request by elias-playfinder**

### CODE REVIEW

**Comment by jordigarciad** [comment]
Please, we need this fix in packagist to avoid continuous deprecated warnings

**Review by necmettin — COMMENTED** [review]
Renaming $Configuration to $config makes no sense. It is pure personal preference and is totally unnecessary. Please fix them back to $Configuration.

**Comment by otis22** [comment]
I've made my own fork with php8 support. I can't wait. For fix: 

```shell
composer rm mailchimp/transactional
composer require otis22/transactional
```

**Comment by Akustik88** [comment]
> I've made my own fork with php8 support. I can't wait. For fix:
> 
> ```shell
> composer rm mailchimp/transactional
> composer require otis22/transactional
> ```

can you fix marketing too? 
https://github.com/mailchimp/mailchimp-marketing-php

**Comment by otis22** [comment]
@Akustik88 I'am sorry. Project does not have tests and I don't use this project in production. I can't be sure I fix it right.

**Comment by PaulMcML** [comment]
> Renaming $Configuration to $config makes no sense. It is pure personal preference and is totally unnecessary. Please fix them back to $Configuration.

This is not just personal preference. The code calls $this->config all over, and that property should be declared. As far as I can see it doesn't call $this->Configuration anywhere.

**Comment by jeremyoppus** [comment]
As @PaulMcML said, the change about $Configuration is also a fix about dynamic property creation, so could you please approve and merge this PR @necmettin ?

Capture d’écran 2024-01-12 à 14 48 19

**Comment by necmettin** [comment]
@jeremyoppus I don't have write access to this repository. All I did was comment.. We are all waiting for @Moishe I think.

**Comment by Moishe** [comment]
I haven't worked at Mailchimp for over 2 years, unfortunately. I'll try to ping some folks.

**Comment by Moishe** [comment]
One thing worth mentioning: as noted in the README, this repo doesn't accept PRs or issues. It's auto-generated from this repo: https://github.com/mailchimp/mailchimp-client-lib-codegen. You might get more traction opening a PR there.

**Comment by necmettin** [comment]
I have actually talked to the support team twice, and they assured me that
the team was working on it. And yet, it's been months.

**Comment by barneyvaughan** [comment]
This can be closed - the newer V1.0.50 has fixed this problem. 

https://github.com/mailchimp/mailchimp-transactional-php/compare/v1.0.50...v1.0.59

**Comment by jordigarciad** [comment]
Version 1.0.59 solved the problem
Thanks!

**Comment by webkod3r** [comment]
Closing as this has been fix already 
see https://github.com/mailchimp/mailchimp-client-lib-codegen/pull/348

Please upgrade to the most recent version, thanks

**Comment by ais8xl** [comment]
@webkod3r Hello, when it will be fixed in mailchimp-marketing (https://github.com/mailchimp/mailchimp-marketing-php)?
Please someone from mailchimp, alteady fix it :(

**Comment by barneyvaughan** [comment]
> @webkod3r Hello, when it will be fixed in mailchimp-marketing (https://github.com/mailchimp/mailchimp-marketing-php)? Please someone from mailchimp, alteady fix it :(

Potentially worth linking this PR to that repo as an issue if you're experiencing it there. Not sure if that one relies on the transactional code so you may well be falling on deaf ears here.

**Comment by webresh** [comment]
> @webkod3r Hello, when it will be fixed in mailchimp-marketing (https://github.com/mailchimp/mailchimp-marketing-php)? Please someone from mailchimp, alteady fix it :(

Hi there, thanks to your comment I realized that no one will help us :)
So I used a temporary fix by adding
`#[\AllowDynamicProperties]`
right before this line
https://github.com/mailchimp/mailchimp-marketing-php/blob/c1a38f7248d8de7de412418fed8dae759b9e4b97/lib/Configuration.php#L50

**Comment by webkod3r** [comment]
Hello guys, I no longer work for Mailchimp. Before leaving the company I voiced this issue and they were going to take care of it. Apparently that was not the case 😪 my apologies on their end. The transactional API and the Marketing API are 2 different APIs. I was working directly with TX API and took care of dynamic properties. That's solved on TX.

**Pull request closed without merging**
